import { test, expect } from '@playwright/test';

test('complete a real race, submit it, and retrieve the persisted public and personal ranking', async ({ page, browser }) => {
  test.setTimeout(180000);
  await page.addInitScript(() => { if (window === window.top) localStorage.setItem('boostrack.v2.settings', JSON.stringify({quality:'low', music:0, sfx:0})); });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/?qa=1');
  await expect(page.locator('#menu')).toBeVisible();
  await page.locator('#ranking-open').click();
  await expect(page.locator('#ranking-mine')).toContainText('아직 등록한');
  await page.keyboard.press('Escape');
  await page.evaluate(async () => {
    const { drive } = await import(/* @vite-ignore */ '/tests/driver.mjs');
    (window as any).__raceTest.setDriver(drive);
  });
  await page.locator('#play').click();
  await expect(page.locator('#dialog-title')).toHaveText('FINISH.', { timeout:120000 });
  await page.locator('.ranking-submit input').fill('QA Racer');
  await page.locator('.ranking-submit button').click();
  await expect(page.locator('.ranking-submit p')).toContainText('등록 완료', { timeout:25000 });
  await page.locator('.ranking-submit button').click();
  await expect(page.locator('#ranking-mine')).toContainText('내 순위');
  const board=await (await page.request.get('/api/leaderboard?track=v2-apex-01')).json();
  const mine=board.entries.find((e:any)=>e.mine);
  const replay=await (await page.request.get(`/api/leaderboard?track=v2-apex-01&replay=${mine.replay}`)).json();
  await page.locator('.ranking-row.is-me button').click();
  await expect.poll(()=>page.evaluate(()=>(window as any).__raceTest.snapshot().state),{timeout:15000}).toBe('running');
  await page.waitForTimeout(1800);
  const snapshot=await page.evaluate(()=>(window as any).__raceTest.snapshot());
  let index=0;while(index<replay.frames.length-2&&replay.frames[index+1].t<snapshot.time)index++;
  const first=replay.frames[index],second=replay.frames[index+1],f=Math.max(0,Math.min(1,(snapshot.time-first.t)/(second.t-first.t)));
  for(let axis=0;axis<3;axis++)expect(snapshot.challengerPosition[axis]).toBeCloseTo(first.p[axis]+(second.p[axis]-first.p[axis])*f,4);
  expect(snapshot.challengerSteering).toBeCloseTo(first.s+(second.s-first.s)*f,5);
  expect(snapshot.challenger.nickname).toBe('QA Racer');
  expect(snapshot.ghostVisible).toBe(false);
  await page.keyboard.press('Escape');
  const frozen=await page.evaluate(()=>(window as any).__raceTest.snapshot().challengerPosition);
  await page.waitForTimeout(200);
  expect(await page.evaluate(()=>(window as any).__raceTest.snapshot().challengerPosition)).toEqual(frozen);
  await page.locator('#back').click();
  await page.locator('#ranking-open').click();
  await expect(page.locator('.ranking-row.is-me')).toContainText('QA Racer');
  await page.screenshot({path:'test-results/ranking-desktop.png'});
  await page.reload();
  await page.locator('#ranking-open').click();
  await expect(page.locator('#ranking-mine')).toContainText('내 순위');
  const other = await browser.newContext({viewport:{width:390,height:844}});
  const mobile = await other.newPage();
  await mobile.goto('http://127.0.0.1:5173/');
  await mobile.locator('#ranking-open').click();
  await expect(mobile.locator('#ranking-entries')).toContainText('QA Racer');
  await expect(mobile.locator('#ranking-mine')).toContainText('아직 등록한');
  await mobile.locator('#ranking-track').selectOption('v2-air-01');
  await expect(mobile.locator('#ranking-entries')).toContainText('첫 번째 기록');
  await mobile.screenshot({path:'test-results/ranking-mobile.png'});
  await other.close();
  expect(errors).toEqual([]);
});

test('ranking reports a server failure with a working retry', async ({page}) => {
  await page.goto('/');
  await page.route('**/api/leaderboard?*', route => route.fulfill({status:503,body:'{}'}));
  await page.locator('#ranking-open').click();
  await expect(page.locator('#ranking-entries')).toContainText('다시 시도');
  await page.unroute('**/api/leaderboard?*');
  await page.locator('#ranking-refresh').click();
  await expect(page.locator('#ranking-mine')).toContainText('아직 등록한');
});
